[metadata]
name = "birth-death example"
description = "Example of a birth-death model"
filename = "birth-death.toml"
author = "Alexander E. Zarebski"
date = "2023-07-31"

[components]
time = "pypfilt.Scalar"
sampler = "pypfilt.sampler.LatinHypercube"
summary = "pypfilt.summary.HDF5"

[time]
start = 0.0
until = 5.0
steps_per_unit = 10
summaries_per_unit = 2

[observations.x]
# model = "birth_death_model.NoisyStateObservation"
model = "birth_death_model.UniformObservation"

[scenario.simulation1a]
simulation_name = "SDE style process (vectorised)"
components.model = "birth_death_model.BirthDeathSDE"
prior.x = { name = "constant", args.value = 2.0 }
prior.death = { name = "constant", args.value = 1.0 }
prior.birth = { name = "constant", args.value = 2.0 }
num_replicates = 100
file = "simu-1a-birth-death-observations.ssv"
plot_path = "out/simulation-sde-vec.png"

[scenario.simulation1b]
simulation_name = "SDE style process (non-vectorised)"
components.model = "birth_death_model.BirthDeathSDENotVec"
prior.x = { name = "constant", args.value = 2.0 }
prior.death = { name = "constant", args.value = 1.0 }
prior.birth = { name = "constant", args.value = 2.0 }
num_replicates = 100
file = "simu-1b-birth-death-observations.ssv"
plot_path = "out/simulation-sde-not-vec.png"

[scenario.simulation2a]
simulation_name = "ODE style process (vectorised)"
components.model = "birth_death_model.BirthDeathODE"
prior.x = { name = "constant", args.value = 2.0 }
prior.death = { name = "constant", args.value = 1.0 }
prior.birth = { name = "constant", args.value = 2.0 }
num_replicates = 10
file = "simu-2a-birth-death-observations.ssv"
plot_path = "out/simulation-ode-vec.png"

[scenario.simulation2b]
simulation_name = "ODE style process (non-vectorised)"
components.model = "birth_death_model.BirthDeathODENotVec"
prior.x = { name = "constant", args.value = 2.0 }
prior.death = { name = "constant", args.value = 1.0 }
prior.birth = { name = "constant", args.value = 2.0 }
num_replicates = 10
file = "simu-2b-birth-death-observations.ssv"
plot_path = "out/simulation-ode-not-vec.png"

[scenario.simulation3a]
simulation_name = "CTMC style process (vectorised)"
components.model = "birth_death_model.BirthDeathCTMC"
prior.x = { name = "constant", args.value = 2.0 }
prior.death = { name = "constant", args.value = 1.0 }
prior.birth = { name = "constant", args.value = 2.0 }
num_replicates = 100
file = "simu-3a-birth-death-observations.ssv"
plot_path = "out/simulation-ctmc-vec.png"

[scenario.simulation3b]
simulation_name = "CTMC style process (non-vectorised)"
components.model = "birth_death_model.BirthDeathCTMCNotVec"
prior.x = { name = "constant", args.value = 2.0 }
prior.death = { name = "constant", args.value = 1.0 }
prior.birth = { name = "constant", args.value = 2.0 }
num_replicates = 100
file = "simu-3b-birth-death-observations.ssv"
plot_path = "out/simulation-ctmc-not-vec.png"

[scenario.simulation4]
simulation_name = "Hybrid style process (non-vectorised)"
components.model = "birth_death_model.BirthDeathHybrid"
prior.x = { name = "constant", args.value = 2.0 }
prior.death = { name = "constant", args.value = 1.0 }
prior.birth = { name = "constant", args.value = 2.0 }
num_replicates = 100
file = "simu-4-birth-death-observations.ssv"
plot_path = "out/simulation-hybrid-not-vec.png"

[filter]
particles = 10
prng_seed = 1
history_window = -1
# resample.threshold = 0.25
# regularisation.enabled = true

# [scenario.forecast]
# summary.tables.model_cints.component = "pypfilt.summary.ModelCIs"
# summary.tables.model_cints.credible_intervals = [ 0, 25, 50, 75, 95 ]
# summary.tables.forecasts.component = "pypfilt.summary.PredictiveCIs"
# summary.tables.forecasts.credible_intervals = [10, 20, 40, 80]
# prior.birth = { name = "uniform", args.loc = 1.75, args.scale = 0.5 }
# backcast_time = 2.0
# forecast_time = 4.0
