[metadata]
name = "SIRS inference example"
description = "Example of an SIRS model inference"
filename = "sirs-inference.toml"
date = "2023-08-22"

[components]
time = "pypfilt.Scalar"
sampler = "pypfilt.sampler.LatinHypercube"
summary = "pypfilt.summary.HDF5"

[time]
start = 0.0
until = 140.0
steps_per_unit = 100
summaries_per_unit = 1

[observations.I]
model = "sirs_model.NoisyStateObservation"
# model = "sirs_model.NegativeBinomailObservation"
# model = "sirs_model.UniformObservation"

[prior]
S = { name = "constant", args.value = 1E4 }
R = { name = "constant", args.value = 0.0 }


[scenario.inference]
components.model = "sirs_model.SIRS_ODE"
# components.model = "sirs_model.SIRS_JSF"
observations.I.file = "out/sim_df.ssv"

prior.I = { name = "constant", args.value = 2.0 }

prior.betaCoef = { name = "uniform", args.loc = 1E-4, args.scale = 4.0 }
prior.gammaCoef = { name = "uniform", args.loc = 1E-4, args.scale = 3.0 }
prior.omegaCoef = { name = "uniform", args.loc = 1E-4, args.scale = 2.0 }
prior.kappaCoef = { name = "constant", args.value = 85.0 }
prior.muCoef = {name = "constant", args.value = 85.0 }

summary.tables.model_cints.component = "pypfilt.summary.ModelCIs"
summary.tables.model_cints.credible_intervals = [ 0, 25, 50, 75, 95 ]
summary.tables.backcasts.component = "sirs_model.BackcastStateCIs"
summary.tables.backcasts.backcast_monitor = "backcast_monitor"
summary.tables.backcasts.credible_intervals = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
summary.tables.point_ests.component = "pypfilt.summary.ModelCIs"
summary.tables.point_ests.credible_intervals = [0, 95]

[filter]
particles = 500
prng_seed = 1
history_window = -1
resample.threshold = 0.25
regularisation.enabled = true

[filter.regularisation.bounds]
# I = { min = 0.0, max = 1E10 }
betaCoef = { min = 1E-4, max = 1E10 }
gammaCoef = { min = 1E-4, max = 1E10 }
omegaCoef = { min = 1E-4, max = 1E10 }
kappaCoef = { min = 1E-4, max = 1E10 }
muCoef = { min = 1E-4, max = 1E10 }

[summary.monitors]
backcast_monitor.component = "pypfilt.summary.BackcastMonitor"
