[metadata]
name = "tiv inference example using simulated data"
description = "Example of a TIV inference from simulated data"
author = "Alexander E. Zarebski"
date = "2023-08-28"

[components]
time = "pypfilt.Scalar"
sampler = "pypfilt.sampler.LatinHypercube"
summary = "pypfilt.summary.HDF5"
model = "src.tiv.TIV_ODE"

[time]
start = 0.0
until = 8.0
steps_per_unit = 200
summaries_per_unit = 1

[observations.V]
model = "src.tiv.Gaussian"
scale = 1.5

[prior]
T = { name = "constant", args.value = 4E8 }
I = { name = "constant", args.value = 0.0 }
beta = { name = "constant", args.value = 3.4E-5 }
p = { name = "constant", args.value = 7.9E-3 }
c = { name = "constant", args.value = 3.3 }
gamma = { name = "constant", args.value = 3.4 }

[scenario.simulation]
prior.V0 = { name = "constant", args.value = 3.5E-1 }

[scenario.inference]
prior.V0 = { name = "uniform", args.loc = 1.0E-1, args.scale = 10.0 }
summary.tables.model_cints.component = "pypfilt.summary.ModelCIs"
summary.tables.model_cints.credible_intervals = [10, 20, 30, 40, 50, 60, 70, 80, 90]
summary.tables.forecasts.component = "pypfilt.summary.PredictiveCIs"
summary.tables.forecasts.credible_intervals = [10, 20, 30, 40, 50, 60, 70, 80, 90]
observations.V.file = "simulated-data-for-inference.ssv"

[filter]
particles = 1000
prng_seed = 1
history_window = -1
resample.threshold = 0.25