[metadata]
name = "tiv inference example using simulated data"
description = "Example of a TIV inference from simulated data"
author = "Alexander E. Zarebski"
date = "2023-08-28"

[components]
time = "pypfilt.Scalar"
sampler = "pypfilt.sampler.LatinHypercube"
summary = "pypfilt.summary.HDF5"
model = "src.tiv.TIV_ODE"

[time]
start = 0.0
until = 8.0
steps_per_unit = 200
summaries_per_unit = 1

[observations.V]
model = "src.tiv.Gaussian"
scale = 1.5

[prior]
T = { name = "constant", args.value = 4E8 }
I = { name = "constant", args.value = 0.0 }

[scenario.simulationP1]
patient_number = 1
prior.V0 = { name = "uniform", args.loc = 1.0E-1, args.scale = 1.0E-1 }
prior.beta = { name = "uniform", args.loc = 1.0E-6, args.scale = 1E-4 }
prior.p = { name = "constant", args.value = 7.9E-3 }
prior.c = { name = "constant", args.value = 3.3 }
prior.gamma = { name = "constant", args.value = 3.4 }
forecast_time = 7.9
summary.tables.model_cints.component = "pypfilt.summary.ModelCIs"
summary.tables.model_cints.credible_intervals = [ 0, 50, 95 ]
summary.tables.forecasts.component = "pypfilt.summary.PredictiveCIs"
summary.tables.forecasts.credible_intervals = [10, 20, 40, 80]
observations.V.file = "out/simulated-data-patient-1-replicte-002.ssv"

[filter]
particles = 1000
prng_seed = 1
history_window = -1
resample.threshold = 0.25
regularisation.enabled = true